static const char *credits = R"**(

${PACKAGE_STRING}


Credits
-------

"yvt" - Most of the code, Japanese translation
"Dany0" - System profiler, ideas, etc.
"learn_more" - CMake support, server browser, ideas, Win32 build guide
"iamgreaser" - AoS 0.76 protocol support
"Ericson2314" - Better installation guide
"JoJoe_Stinky" - Win32 Icon, Killfeed icons
"theunknownxy" - Fixes for the Linux support
"noway421" - Russian translation, various testing, ideas
"pandaro" - Improvements to the Minimap
"kmsi" - Korean translation
"tungdil" - German translation
"feikname" - Brazilian Portuguese translation, GUI ideas, wiki maintenance
"VelocityRa" - Repo maintenance, VS2015 support, better random generator
"Mailaender" - FreeDesktop definitions fixes
"Chameleonhider" - Configurable player name drawing
"CenturionFox" - Server Disconnect Screen
"DarkDracoon" - European Portuguese translation
"BrunoDiazU" - Spanish translation
"teodor6140" - Headshot feedback "whack" sound

And many others which weren't mentioned here.


PrismSpades credits
-------------------

"VierEck.":
MapEditor, Demo Replay/Recording based on aos_replay, Chat Macros, Performance Config
"Ashy.":
Special thanks to you for being my light in the dark, my constant support, and the heart behind so many of PrismSpades' ideas. I couldn’t have done this without you.
"Nuceto":
Killfeed image feature, Specific word message highlight, Colored chat message, Colored stats, HUD and Minimap transparency, Teammate map sector in chat message, HitTest Debug display transparency and size, Default Fade Weapon Models, killfeed distance analisation, improved footstep audio
"ZeroGrey":
PM message highlight, Show map sector, Ignore chat, Hitfeedback sound, Hit analyze message, HitTest Debug improvements, k/d and streak display, damage indicators, Respawn Sound, Intro Sound, Screenshot Sound, Death Sound, Score Messages, Different Playermodels based on Weapon, improved skin models animations, First Person Lower Body, Classic Corpse Bounce Physics, mouse accel toggle, voxlap zoom filter, classic view weapon, improved weapon animation, Falling Blocks Bounce Physics, throttle minimap updates, hold map zoom, playing time in scoreboard, custom target and scope, improved GUI Design, physical based shading for models
"Mile":
Glitter, Title Map "HallWeeb.vxl",
"nonperforming":
QWE to select team, turn off falling blocks, turn off corpses
"Doctor Dank":
PubOVL
"BR":
aos_replay, throttle send orientatian time, HitTest Debug display, pickaxe when single digging
"Liza":
Block color Inverting and Mixing
"utf":
MacOs 9 Platinum Sounds for GUI and Alert, Headshot sound.
"ptrstr":
next Spawn Loadout
"paratrooper":
improved weapon animation based on paratrooper's M14 Remastered
"JimPix":
Inspiration for: spectator NoFogMixing, recoil adjustments, hottrack player names enhancements
"MuffinTastic":
Glow Blocks
"sovenance":
Original hit analyze message
"iSkyte":
Killfeed images


Translators
-----------

- Brazilian Portuguese: "feikname"
- Dutch: "Tapmemer"
- European Portuguese: "DarkDracoon"
- French: "damienflament"
- German: "tungdil", "NotAFile", "theunknownxy"
- Japanese: "yvt"
- Korean: "kmsi"
- Polish: João Rodrigues
- Russian: "noway421", "ArionWT"
- Spanish: "BrunoDiazU"


Portions of program is based on following software
---------------------------------------------------

pyspades

Licensed by GPLv3. CREDITS/CONTRIBUTIONS/ACKNOWLEDGEMENTS:

Mathias "Mat^2" Kaerlev - Most of the code
"hompy" - Floating block detection, IRC client, general code, etc.
"Triplefox" - Map generator code, network code, etc.
"Sham" - Hosting and testing
"Yourself" - Scripts
"bildramer" - Floating block detection (A*) and misc. code
"TheGrandmaster" - Tester, ideas and the official map
"Tegu" - Logo, ideas, testing and the official map
"Enari" - Testing, misc. code and ideas


This program includes following components
------------------------------------------

- AngelCode Scripting Library

Copyright (C) 2003-2013 Andreas Jönsson

This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

 * The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.
 * Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
 * This notice may not be removed or altered from any source distribution.


- ENet

Copyright (C) 2002-2011 Lee Salzman

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


- Kiss FFT

Copyright (C) 2003-2010 Mark Borgerding. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the author nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


)**";
